### ISSUE TITLE
We need to add floating_network_name to the network section

### ISSUE THREAD

**Issue by itzikb-redhat** [redhat-openstack/python-tempestconf#3]
When running tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario
it fails with error Floating IP pool not found. 

There is a need to add floating_network_name in the network section with the value of the external network name

**Comment by ltoscano-rh** [comment]
Interesting; if you hit it by using this configurator, should the fix be added to the existing redhat-openstack/tempest as well? (I think we would have seen it already, so maybe there is a regression in the port?)

**Comment by itzikb-redhat** [comment]
I'm facing the same issue with redhat-openstack/tempest as well.

**Comment by danielmellado** [comment]
Please do take into consideration that there are several values that *can't* be discovered. Instead, TripleO is feeding the config tool/tempest fork with such details, so consider that when opening issues here.
