### ISSUE TITLE
Merge configuration in default-overrides.conf into etc/tempest.conf

### ISSUE THREAD

**Issue by amoralej** [redhat-openstack/python-tempestconf#4]
According to the info in old config_tempest.py ( https://github.com/redhat-openstack/tempest/blob/master/tools/config_tempest.py#L18-L23 ), it merged configuration items in /etc/tempest/default-overrides.conf into etc/tempest.conf. 

This is not working after separating it into a different package and it's forcing users to add it as a --deployer-input which is not convenient for users as they may need to pass other customized deployer input file.

**Comment by chkumar246** [comment]
https://review.gerrithub.io/#/c/344989/ will fix the issue
