### ISSUE TITLE
Auto discovery of number of running compute nodes

### ISSUE THREAD

**Issue by mpryc** [redhat-openstack/python-tempestconf#5]
min_compute_nodes tells:

The minimum number of compute nodes expected. This will be utilized
by some multinode specific tests to ensure that requests match the
expected size of the cluster you are testing with. (integer value)
min_compute_nodes = 1

If the number is left default 1, then migration tempest tests are skipped.

IMO this number should be auto discovered before running tempest config.

**Comment by apevec** [comment]
python-tempestconf is moved to OpenStack http://git.openstack.org/cgit/openstack/python-tempestconf Please use OpenStack gerrit https://review.openstack.org to submit patches.
